"""COMMIT target for the CONVENTION artifact: write a kept *convention* into a
file Claude Code loads as context.

A CONVENTION is the SOFT sibling of a Rule (the procedural-memory artifact): a
standing convention/preference
("API handlers live in src/api/", "prefer composition over inheritance") that can't
be a deterministic gate, so it's delivered as context, never enforced. We never claim
a tier for it.

Mechanism (verified against code.claude.com/docs/en/memory, 2026-06-30): Claude Code's
own docs do NOT endorse third-party tools editing the user's CLAUDE.md in place; the
recommended pattern is a DECOUPLED file the tool fully owns, surfaced via the native
`.claude/rules/` directory. So Precept owns dedicated generated files there and NEVER
splices into the user's hand-written CLAUDE.md:

  - GLOBAL   -> ~/.claude/rules/precept-conventions.md      (no `paths:` -> loads always)
  - REPO     -> <repo_root>/.claude/rules/precept-conventions.md
  - LANGUAGE -> ~/.claude/rules/precept-<marker>.md         (`paths:` globs -> lazy-load)

Because Precept owns the WHOLE file, idempotency is "regenerate the file", uninstall is
"delete the file", and there's zero risk to user content (no marker bookkeeping). A
sidecar MANIFEST in the local state dir records the paths we wrote, so a recompile or
uninstall removes ONLY files Precept created (a repo whose last convention was archived
gets its file deleted), never the user's own `.claude/rules/*.md`.

Boundary (mirrors `bootstrap.py`'s permission boundary): we write back only conventions
Precept LEARNED. A CONVENTION lesson with origin=BOOTSTRAP was imported FROM the user's
own CLAUDE.md, so re-emitting it would duplicate the directive in context — those are
skipped, exactly as Precept never re-adopts the user's pre-existing permission entries.
"""

from __future__ import annotations

import json
from pathlib import Path

from . import paths
from .models import ArtifactType, Lesson, Origin, Scope, Status
from .safety import atomic_write_text

_RULES_DIRNAME = "rules"
_DEFAULT_STEM = "precept-conventions"
_HEADER = "<!-- Generated by Precept — do not edit. Managed via `precept keep` / `precept delete`. -->"

# Anthropic guidance: keep a memory/rules file lean — adherence degrades as a CLAUDE.md /
# rules file grows (target well under ~200 lines; rules start dropping past ~80). An
# always-loaded GLOBAL conventions file is exactly the kind that can bloat, so we WARN (never
# block) past this, biasing the user toward narrower scope / decay. (code.claude.com/docs/en/memory)
MAX_RECOMMENDED_LINES = 200

# A LANGUAGE-scoped convention compiles to a `.claude/rules/precept-<marker>.md` with a
# `paths:` glob so Claude Code lazy-loads it only when a file of that language is touched.
# Conservative + honest: an unknown marker falls back to no `paths:` (loads unconditionally
# at user level) rather than guessing a wrong glob.
LANG_GLOBS: dict[str, list[str]] = {
    "python": ["**/*.py"],
    "node": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
    "javascript": ["**/*.js", "**/*.jsx"],
    "typescript": ["**/*.ts", "**/*.tsx"],
    "go": ["**/*.go"],
    "rust": ["**/*.rs"],
    "ruby": ["**/*.rb"],
    "java": ["**/*.java"],
    "csharp": ["**/*.cs"],
    "cpp": ["**/*.cpp", "**/*.cc", "**/*.hpp", "**/*.h"],
}


# ---------------------------------------------------------------------------
# Placement: a lesson's scope decides which file it belongs in.
# ---------------------------------------------------------------------------
def is_managed(lesson: Lesson) -> bool:
    """True for an ACTIVE convention Precept should WRITE BACK as soft context.

    Excluded:
      - non-CONVENTION artifacts;
      - non-ACTIVE (pending/archived) lessons;
      - BOOTSTRAP-imported directives — they already live in the user's CLAUDE.md (see
        module docstring), so re-emitting would duplicate context;
      - a lesson that ALSO compiled to a HARD policy. If the classifier tagged a
        convention `judgment` and `keep` synthesized a Stop verdict gate, it is already
        enforced; writing it ALSO as a soft rules line would double-implement the same
        learning (a hard gate + a soft reminder). The hard policy wins; we stay quiet."""
    return (
        lesson.artifact_type == ArtifactType.CONVENTION
        and lesson.status == Status.ACTIVE
        and lesson.origin != Origin.BOOTSTRAP
        and not lesson.policies
    )


def _lang_globs(marker: str | None) -> list[str] | None:
    if not marker:
        return None
    return LANG_GLOBS.get(marker.strip().lower())


def target_for(lesson: Lesson) -> Path | None:
    """The file this convention is written into, or None if it can't be placed
    (a REPO lesson with no resolved root — defensive; mirrors compile.py)."""
    if lesson.scope == Scope.REPO:
        if not lesson.scope_value:
            return None
        return Path(lesson.scope_value) / ".claude" / _RULES_DIRNAME / f"{_DEFAULT_STEM}.md"
    if lesson.scope == Scope.LANGUAGE and lesson.scope_value:
        marker = lesson.scope_value.strip().lower()
        return paths.claude_home() / _RULES_DIRNAME / f"precept-{marker}.md"
    # GLOBAL (and a LANGUAGE lesson with no marker) -> the user-level conventions file.
    return paths.claude_home() / _RULES_DIRNAME / f"{_DEFAULT_STEM}.md"


# ---------------------------------------------------------------------------
# Rendering: a file's content is a pure function of the ACTIVE lessons in it.
# ---------------------------------------------------------------------------
def render_file(lessons: list[Lesson], *, globs: list[str] | None = None) -> str:
    """Render one rules file. Deterministic (lessons sorted by id) so a recompile of
    the same catalog is byte-for-byte stable. `globs` (LANGUAGE only) become a `paths:`
    frontmatter so Claude Code path-scopes the file."""
    ordered = sorted(lessons, key=lambda le: le.id)
    parts: list[str] = []
    if globs:
        fm = "\n".join(f'  - "{g}"' for g in globs)
        parts.append(f"---\npaths:\n{fm}\n---")
    parts.append(_HEADER)
    parts.append("# Conventions (managed by Precept)\n")
    body = "\n".join(f"- {le.what_to_do_instead.strip()}" for le in ordered)
    parts.append(body + "\n")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Sidecar manifest: the set of files Precept last wrote (local/derived).
# ---------------------------------------------------------------------------
def _load_manifest() -> list[str]:
    try:
        data = json.loads(paths.managed_conventions_manifest().read_text(encoding="utf-8"))
        if isinstance(data, dict):
            files = data.get("files", [])
            if isinstance(files, list):
                return [str(f) for f in files]
    except (OSError, ValueError):
        pass
    return []


def _save_manifest(files: list[str]) -> None:
    paths.ensure_dirs()
    payload = {"files": sorted(set(files))}
    atomic_write_text(
        paths.managed_conventions_manifest(), json.dumps(payload, indent=2) + "\n"
    )


def _remove_file(path: Path) -> None:
    """Delete a managed file and prune an empty `.claude/rules` we created (best-effort)."""
    try:
        path.unlink(missing_ok=True)
    except OSError:
        return
    parent = path.parent  # .../rules
    try:
        if parent.name == _RULES_DIRNAME and not any(parent.iterdir()):
            parent.rmdir()
    except OSError:
        pass


# ---------------------------------------------------------------------------
# The COMMIT entrypoints, called from compile / uninstall.
# ---------------------------------------------------------------------------
def write_managed_rules(lessons: list[Lesson]) -> list[Path]:
    """Sync Precept's managed convention files from the catalog: write the file for
    every group of ACTIVE learned conventions, and delete any file we previously wrote
    that no longer has backing lessons. Returns the files that now exist.

    Idempotent (deterministic render + same grouping), atomic (.bak-free small files via
    atomic_write_text), and self-cleaning (the manifest drives stale-file removal)."""
    managed = [le for le in lessons if is_managed(le)]
    # Group by destination file; a LANGUAGE file's marker comes from its first lesson
    # (all lessons in that file share the marker by construction of the filename).
    groups: dict[str, list[Lesson]] = {}
    for le in managed:
        dest = target_for(le)
        if dest is None:  # unplaceable (repo lesson with no root) -> skip defensively
            continue
        groups.setdefault(str(dest), []).append(le)

    written: list[str] = []
    for dest_str, group in groups.items():
        dest = Path(dest_str)
        marker = group[0].scope_value if group[0].scope == Scope.LANGUAGE else None
        atomic_write_text(dest, render_file(group, globs=_lang_globs(marker)))
        written.append(dest_str)

    # Remove files we wrote last time that are no longer backed (de-duped, atomic manifest).
    desired = set(written)
    for stale in _load_manifest():
        if stale not in desired:
            _remove_file(Path(stale))
    _save_manifest(written)
    return [Path(w) for w in sorted(desired)]


def strip_all() -> list[Path]:
    """Delete every file Precept manages (uninstall). Exact inverse of a sync from a
    clean state. Returns the removed paths."""
    removed = [Path(f) for f in _load_manifest()]
    for p in removed:
        _remove_file(p)
    _save_manifest([])
    return removed


def managed_files() -> list[Path]:
    """The currently-managed convention files (per the manifest), for `precept doctor`."""
    return [Path(f) for f in _load_manifest()]


def oversize_files(threshold: int = MAX_RECOMMENDED_LINES) -> list[tuple[Path, int]]:
    """Managed files whose line count exceeds the lean-memory threshold, as (path, lines).
    A guardrail for Anthropic's keep-memory-short guidance: surfaced by `precept doctor`
    so a bloated always-on conventions file is visible (warn, never block)."""
    out: list[tuple[Path, int]] = []
    for p in managed_files():
        try:
            n = sum(1 for _ in p.open(encoding="utf-8"))
        except OSError:
            continue
        if n > threshold:
            out.append((p, n))
    return out
